name: Deploy prod closures-and-restrictions-map

on:
  push:
    tags:
      - "prod-closures-and-restrictions-map-v*"
      - "prod-all-v*"

jobs:
  Deploy:
    name: Deploy prod closures-and-restrictions-map
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 20.9.0
          cache: "npm"
      - run: npm ci
      - run: npm run build --workspace=@bratislava/closures-and-restrictions-map
      - uses: lovellfelix/minio-deploy-action@1f4fafcee58750ebe8f726d33a55d926d2224065 # v1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: "static-pages"
          source_dir: "apps/closures-and-restrictions-map/dist"
          target_dir: "/closures-and-restrictions-map"
