name: Deploy prod planting-map

on:
  push:
    tags:
      - "prod-planting-map-v*"
      - "prod-all-v*"

jobs:
  Deploy:
    name: Deploy prod planting-map
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 20.9.0
          cache: "npm"
      - run: npm ci
      - run: npm run build --workspace=@bratislava/planting-map
      - name: Upload to MinIO
        env:
          MC_VERSION: RELEASE.2025-08-13T08-35-41Z
          MC_SHA256: 01f866e9c5f9b87c2b09116fa5d7c06695b106242d829a8bb32990c00312e891
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        run: |
          curl --silent --show-error --location --fail --output "$RUNNER_TEMP/mc" "https://github.com/minio/mc/releases/download/$MC_VERSION/mc.linux-amd64.$MC_VERSION"
          echo "$MC_SHA256  $RUNNER_TEMP/mc" | sha256sum --check
          chmod +x "$RUNNER_TEMP/mc"
          "$RUNNER_TEMP/mc" alias set deploy "$MINIO_ENDPOINT" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
          "$RUNNER_TEMP/mc" cp --recursive apps/planting-map/dist/ deploy/static-pages/planting-map/
