name: Deploy prod cvicko-map

on:
  push:
    tags:
      - "prod-cvicko-map-v*"

jobs:
  Deploy:
    name: Deploy prod cvicko-map
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @bratislava/cvicko-map build
      - uses: lovellfelix/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: "static-pages"
          source_dir: "apps/cvicko-map/dist"
          target_dir: "/cvicko-map"
