name: Deploy prod paas-map

on:
  push:
    tags:
      - 'prod-paas-map-v*'

jobs:
  Deploy:
    name: Deploy prod paas-map
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @bratislava/paas-map build 
      - uses: lovellfelix/minio-deploy-action@v1
        with:
          node-version: 16.x
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'static-pages'
          source_dir: 'apps/paas-map/dist'
          target_dir: '/paas-map'
