name: Deploy staging drinking-fountains-map

on:
  push:
    branches:
      - master
jobs:
  Deploy:
    name: Deploy staging drinking-fountains-map
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @bratislava/drinking-fountains-map build 
      - uses: lovellfelix/minio-deploy-action@v1
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: "static-pages"
          source_dir: "apps/drinking-fountains-map/dist"
          target_dir: "/dev/drinking-fountains-map"
