name: Deploy staging closures-and-restrictions

on: [pull_request]
jobs:
  Deploy:
    name: Deploy staging closures-and-restrictions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @bratislava/closures-and-restrictions build 
      - uses: lovellfelix/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'static-pages'
          source_dir: 'apps/closures-and-restrictions/dist'
          target_dir: '/dev/closures-and-restrictions'
